// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhpwzeopjuxfaefgusao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpocHd6ZW9wanV4ZmFlZmd1c2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzEyNzgsImV4cCI6MjA1OTg0NzI3OH0.FzGVfr3yALOFWmIearF3gfr-Z_6WcAPiqzgA8H6M2xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);